### ISSUE TITLE
Rimworld error

### ISSUE THREAD

**Issue by frenchiveruti** [AlcoholV/Rim.AcEnhancedCrafting#1]
Mod Rim.AcEnhancedCrafting-1.12 has incorrectly formatted target version 'Unknown'. For the current version, write: <targetVersion>0.16.1393</targetVersion>

**Comment by mindryu** [comment]
That's because you did not install the mod properly.

**Comment by frenchiveruti** [comment]
Oooh I see, this is related then to what I reported before at  #2 Because github makes you download the entire source.
Maybe a "wiki" file in here so it points out that the folders have to be placed on the rimworld main directory?
There's no such thing on the ludeon forum post :(
