### ISSUE TITLE
Missing download file on release

### ISSUE THREAD

**Issue by frenchiveruti** [AlcoholV/Rim.AcEnhancedCrafting#2]
It allows the user to download the source code, with all the github clutter with it.

**Comment by mindryu** [comment]
Yes, it is.... That's what git is...

**Comment by frenchiveruti** [comment]
Ah ok sorry, it's just that most other mods that use Github as a platform usually attach a zip file to the releases, take for example 
https://github.com/zorbathut/oshacompliance/releases/tag/v1.0.2
Or many others, if it is like this, then no problem!

**Comment by mindryu** [comment]
I've attached a zip file for unfamiliar people to git.
